const SET_LOGIN = 'SET_LOGIN'
const SET_LOGOUT = 'SET_LOGOUT'
const SET_LOGIN_USER_DATA = 'SET_LOGIN_USER_DATA'
const SET_FAVORITE_LIST_DATA = 'SET_FAVORITE_LIST_DATA'
const ADD_NOTIFICATION_DATA = 'ADD_NOTIFICATION_DATA'

export {
    SET_LOGIN,
    SET_LOGOUT,
    SET_LOGIN_USER_DATA,
    SET_FAVORITE_LIST_DATA,
    ADD_NOTIFICATION_DATA
}